version: "3.4"
x-common-variables: &common-variables
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: example
  MONGO_INITDB_DATABASE: sampledb
  REACT_APP_SERVER_PORT: 8000
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      <<: *common-variables
    ports:
      - 27017:27017
    restart: unless-stopped
  recipeapi:
    build: ./recipeApi
    container_name: recipeapi
    depends_on:
      - mongodb
    environment:
      <<: *common-variables
      MONGO_HOST: mongodb
    ports:
      - 3001:3001
    volumes:
      - ./recipeApi:/app
    command: npm start
  client:
    build: ./client
    container_name: client
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 8080:3000
    volumes:
      - ./client/src:/app/src
    links:
      - recipeapi
    command: npm start

